version: '3'
services:
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    volumes:
      - ./loki/data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    container_name: grafana
  vector:
    image: timberio/vector:0.X-alpine
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      # - ./vector/vector.toml:/etc/vector/vector.toml
    container_name: vector
    depends_on:
      - loki
  reporter:
    build: .
    environment:
      CLASH_HOST: '192.168.88.201:9090'
      CLASH_TOKEN: ''
      VECTOR_ADDR: 'vector:9000'
    container_name: reporter
    depends_on:
      - vector
