{
 "title": "Clash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "域名访问次数",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "ProxyDial",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "慢 Dial",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 6, "y": 0 },
   "targets": [
    {
     "measurement": "ProxyDial",
     "select": [
      [
       { "params": [ "address" ], "type": "field" }
      ],
      [
       { "params": [ "proxy" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "duration", "operator": ">", "value": "200000" }
     ]
    }
   ]
  },
  {
   "title": "局域网访问",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "RuleMatch",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "规则匹配速度",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "RuleMatch",
     "query": "SELECT mean(\"value\") FROM \"RuleMatch\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "流量统计",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Traffic",
     "query": "SELECT sum(\"upload\")+sum(\"download\") FROM \"Traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Traffic",
     "query": "SELECT sum(\"upload\")+sum(\"download\") FROM \"Traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS 平均查询时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DNSRequest",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "代理 Dial 时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "ProxyDial",
     "query": "SELECT mean(\"duration\") FROM \"ProxyDial\" WHERE $timeFilter GROUP BY time(10s), \"proxy\" fill(0)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "实时流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Traffic",
     "query": "SELECT mean(\"value\") FROM \"Traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Traffic",
     "query": "SELECT mean(\"value\") FROM \"Traffic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS 查询",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "DNSRequest",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "慢 DNS 查询",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "measurement": "DNSRequest",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "qType" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "duration", "operator": ">", "value": "200000" }
     ]
    }
   ]
  }
 ]
}